# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/cmake-3.7.2-Linux-x86_64/bin/cmake

# The command to remove a file.
RM = /opt/cmake-3.7.2-Linux-x86_64/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /DIST/home/lab_espl_stud04/espl_workspace/Demo_STM_CMAKE

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /DIST/home/lab_espl_stud04/espl_workspace/Demo_STM_CMAKE

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/cmake-3.7.2-Linux-x86_64/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/cmake-3.7.2-Linux-x86_64/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /DIST/home/lab_espl_stud04/espl_workspace/Demo_STM_CMAKE/CMakeFiles /DIST/home/lab_espl_stud04/espl_workspace/Demo_STM_CMAKE/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /DIST/home/lab_espl_stud04/espl_workspace/Demo_STM_CMAKE/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named flash

# Build rule for target.
flash: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 flash
.PHONY : flash

# fast build rule for target.
flash/fast:
	$(MAKE) -f CMakeFiles/flash.dir/build.make CMakeFiles/flash.dir/build
.PHONY : flash/fast

#=============================================================================
# Target rules for targets named ugfxlib

# Build rule for target.
ugfxlib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ugfxlib
.PHONY : ugfxlib

# fast build rule for target.
ugfxlib/fast:
	$(MAKE) -f CMakeFiles/ugfxlib.dir/build.make CMakeFiles/ugfxlib.dir/build
.PHONY : ugfxlib/fast

#=============================================================================
# Target rules for targets named usrlib

# Build rule for target.
usrlib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 usrlib
.PHONY : usrlib

# fast build rule for target.
usrlib/fast:
	$(MAKE) -f CMakeFiles/usrlib.dir/build.make CMakeFiles/usrlib.dir/build
.PHONY : usrlib/fast

#=============================================================================
# Target rules for targets named Demo.bin

# Build rule for target.
Demo.bin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Demo.bin
.PHONY : Demo.bin

# fast build rule for target.
Demo.bin/fast:
	$(MAKE) -f CMakeFiles/Demo.bin.dir/build.make CMakeFiles/Demo.bin.dir/build
.PHONY : Demo.bin/fast

#=============================================================================
# Target rules for targets named stmutilitieslib

# Build rule for target.
stmutilitieslib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 stmutilitieslib
.PHONY : stmutilitieslib

# fast build rule for target.
stmutilitieslib/fast:
	$(MAKE) -f CMakeFiles/stmutilitieslib.dir/build.make CMakeFiles/stmutilitieslib.dir/build
.PHONY : stmutilitieslib/fast

#=============================================================================
# Target rules for targets named rtoslib

# Build rule for target.
rtoslib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rtoslib
.PHONY : rtoslib

# fast build rule for target.
rtoslib/fast:
	$(MAKE) -f CMakeFiles/rtoslib.dir/build.make CMakeFiles/rtoslib.dir/build
.PHONY : rtoslib/fast

#=============================================================================
# Target rules for targets named Demo.elf

# Build rule for target.
Demo.elf: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Demo.elf
.PHONY : Demo.elf

# fast build rule for target.
Demo.elf/fast:
	$(MAKE) -f CMakeFiles/Demo.elf.dir/build.make CMakeFiles/Demo.elf.dir/build
.PHONY : Demo.elf/fast

#=============================================================================
# Target rules for targets named stmperipheralslib

# Build rule for target.
stmperipheralslib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 stmperipheralslib
.PHONY : stmperipheralslib

# fast build rule for target.
stmperipheralslib/fast:
	$(MAKE) -f CMakeFiles/stmperipheralslib.dir/build.make CMakeFiles/stmperipheralslib.dir/build
.PHONY : stmperipheralslib/fast

Libraries/FreeRTOS/FreeRTOS/Demo/Common/Minimal/flash.o: Libraries/FreeRTOS/FreeRTOS/Demo/Common/Minimal/flash.c.o

.PHONY : Libraries/FreeRTOS/FreeRTOS/Demo/Common/Minimal/flash.o

# target to build an object file
Libraries/FreeRTOS/FreeRTOS/Demo/Common/Minimal/flash.c.o:
	$(MAKE) -f CMakeFiles/rtoslib.dir/build.make CMakeFiles/rtoslib.dir/Libraries/FreeRTOS/FreeRTOS/Demo/Common/Minimal/flash.c.o
.PHONY : Libraries/FreeRTOS/FreeRTOS/Demo/Common/Minimal/flash.c.o

Libraries/FreeRTOS/FreeRTOS/Demo/Common/Minimal/flash.i: Libraries/FreeRTOS/FreeRTOS/Demo/Common/Minimal/flash.c.i

.PHONY : Libraries/FreeRTOS/FreeRTOS/Demo/Common/Minimal/flash.i

# target to preprocess a source file
Libraries/FreeRTOS/FreeRTOS/Demo/Common/Minimal/flash.c.i:
	$(MAKE) -f CMakeFiles/rtoslib.dir/build.make CMakeFiles/rtoslib.dir/Libraries/FreeRTOS/FreeRTOS/Demo/Common/Minimal/flash.c.i
.PHONY : Libraries/FreeRTOS/FreeRTOS/Demo/Common/Minimal/flash.c.i

Libraries/FreeRTOS/FreeRTOS/Demo/Common/Minimal/flash.s: Libraries/FreeRTOS/FreeRTOS/Demo/Common/Minimal/flash.c.s

.PHONY : Libraries/FreeRTOS/FreeRTOS/Demo/Common/Minimal/flash.s

# target to generate assembly for a file
Libraries/FreeRTOS/FreeRTOS/Demo/Common/Minimal/flash.c.s:
	$(MAKE) -f CMakeFiles/rtoslib.dir/build.make CMakeFiles/rtoslib.dir/Libraries/FreeRTOS/FreeRTOS/Demo/Common/Minimal/flash.c.s
.PHONY : Libraries/FreeRTOS/FreeRTOS/Demo/Common/Minimal/flash.c.s

Libraries/FreeRTOS/FreeRTOS/Source/list.o: Libraries/FreeRTOS/FreeRTOS/Source/list.c.o

.PHONY : Libraries/FreeRTOS/FreeRTOS/Source/list.o

# target to build an object file
Libraries/FreeRTOS/FreeRTOS/Source/list.c.o:
	$(MAKE) -f CMakeFiles/rtoslib.dir/build.make CMakeFiles/rtoslib.dir/Libraries/FreeRTOS/FreeRTOS/Source/list.c.o
.PHONY : Libraries/FreeRTOS/FreeRTOS/Source/list.c.o

Libraries/FreeRTOS/FreeRTOS/Source/list.i: Libraries/FreeRTOS/FreeRTOS/Source/list.c.i

.PHONY : Libraries/FreeRTOS/FreeRTOS/Source/list.i

# target to preprocess a source file
Libraries/FreeRTOS/FreeRTOS/Source/list.c.i:
	$(MAKE) -f CMakeFiles/rtoslib.dir/build.make CMakeFiles/rtoslib.dir/Libraries/FreeRTOS/FreeRTOS/Source/list.c.i
.PHONY : Libraries/FreeRTOS/FreeRTOS/Source/list.c.i

Libraries/FreeRTOS/FreeRTOS/Source/list.s: Libraries/FreeRTOS/FreeRTOS/Source/list.c.s

.PHONY : Libraries/FreeRTOS/FreeRTOS/Source/list.s

# target to generate assembly for a file
Libraries/FreeRTOS/FreeRTOS/Source/list.c.s:
	$(MAKE) -f CMakeFiles/rtoslib.dir/build.make CMakeFiles/rtoslib.dir/Libraries/FreeRTOS/FreeRTOS/Source/list.c.s
.PHONY : Libraries/FreeRTOS/FreeRTOS/Source/list.c.s

Libraries/FreeRTOS/FreeRTOS/Source/portable/MemMang/heap_1.o: Libraries/FreeRTOS/FreeRTOS/Source/portable/MemMang/heap_1.c.o

.PHONY : Libraries/FreeRTOS/FreeRTOS/Source/portable/MemMang/heap_1.o

# target to build an object file
Libraries/FreeRTOS/FreeRTOS/Source/portable/MemMang/heap_1.c.o:
	$(MAKE) -f CMakeFiles/rtoslib.dir/build.make CMakeFiles/rtoslib.dir/Libraries/FreeRTOS/FreeRTOS/Source/portable/MemMang/heap_1.c.o
.PHONY : Libraries/FreeRTOS/FreeRTOS/Source/portable/MemMang/heap_1.c.o

Libraries/FreeRTOS/FreeRTOS/Source/portable/MemMang/heap_1.i: Libraries/FreeRTOS/FreeRTOS/Source/portable/MemMang/heap_1.c.i

.PHONY : Libraries/FreeRTOS/FreeRTOS/Source/portable/MemMang/heap_1.i

# target to preprocess a source file
Libraries/FreeRTOS/FreeRTOS/Source/portable/MemMang/heap_1.c.i:
	$(MAKE) -f CMakeFiles/rtoslib.dir/build.make CMakeFiles/rtoslib.dir/Libraries/FreeRTOS/FreeRTOS/Source/portable/MemMang/heap_1.c.i
.PHONY : Libraries/FreeRTOS/FreeRTOS/Source/portable/MemMang/heap_1.c.i

Libraries/FreeRTOS/FreeRTOS/Source/portable/MemMang/heap_1.s: Libraries/FreeRTOS/FreeRTOS/Source/portable/MemMang/heap_1.c.s

.PHONY : Libraries/FreeRTOS/FreeRTOS/Source/portable/MemMang/heap_1.s

# target to generate assembly for a file
Libraries/FreeRTOS/FreeRTOS/Source/portable/MemMang/heap_1.c.s:
	$(MAKE) -f CMakeFiles/rtoslib.dir/build.make CMakeFiles/rtoslib.dir/Libraries/FreeRTOS/FreeRTOS/Source/portable/MemMang/heap_1.c.s
.PHONY : Libraries/FreeRTOS/FreeRTOS/Source/portable/MemMang/heap_1.c.s

Libraries/FreeRTOS/FreeRTOS/Source/queue.o: Libraries/FreeRTOS/FreeRTOS/Source/queue.c.o

.PHONY : Libraries/FreeRTOS/FreeRTOS/Source/queue.o

# target to build an object file
Libraries/FreeRTOS/FreeRTOS/Source/queue.c.o:
	$(MAKE) -f CMakeFiles/rtoslib.dir/build.make CMakeFiles/rtoslib.dir/Libraries/FreeRTOS/FreeRTOS/Source/queue.c.o
.PHONY : Libraries/FreeRTOS/FreeRTOS/Source/queue.c.o

Libraries/FreeRTOS/FreeRTOS/Source/queue.i: Libraries/FreeRTOS/FreeRTOS/Source/queue.c.i

.PHONY : Libraries/FreeRTOS/FreeRTOS/Source/queue.i

# target to preprocess a source file
Libraries/FreeRTOS/FreeRTOS/Source/queue.c.i:
	$(MAKE) -f CMakeFiles/rtoslib.dir/build.make CMakeFiles/rtoslib.dir/Libraries/FreeRTOS/FreeRTOS/Source/queue.c.i
.PHONY : Libraries/FreeRTOS/FreeRTOS/Source/queue.c.i

Libraries/FreeRTOS/FreeRTOS/Source/queue.s: Libraries/FreeRTOS/FreeRTOS/Source/queue.c.s

.PHONY : Libraries/FreeRTOS/FreeRTOS/Source/queue.s

# target to generate assembly for a file
Libraries/FreeRTOS/FreeRTOS/Source/queue.c.s:
	$(MAKE) -f CMakeFiles/rtoslib.dir/build.make CMakeFiles/rtoslib.dir/Libraries/FreeRTOS/FreeRTOS/Source/queue.c.s
.PHONY : Libraries/FreeRTOS/FreeRTOS/Source/queue.c.s

Libraries/FreeRTOS/FreeRTOS/Source/tasks.o: Libraries/FreeRTOS/FreeRTOS/Source/tasks.c.o

.PHONY : Libraries/FreeRTOS/FreeRTOS/Source/tasks.o

# target to build an object file
Libraries/FreeRTOS/FreeRTOS/Source/tasks.c.o:
	$(MAKE) -f CMakeFiles/rtoslib.dir/build.make CMakeFiles/rtoslib.dir/Libraries/FreeRTOS/FreeRTOS/Source/tasks.c.o
.PHONY : Libraries/FreeRTOS/FreeRTOS/Source/tasks.c.o

Libraries/FreeRTOS/FreeRTOS/Source/tasks.i: Libraries/FreeRTOS/FreeRTOS/Source/tasks.c.i

.PHONY : Libraries/FreeRTOS/FreeRTOS/Source/tasks.i

# target to preprocess a source file
Libraries/FreeRTOS/FreeRTOS/Source/tasks.c.i:
	$(MAKE) -f CMakeFiles/rtoslib.dir/build.make CMakeFiles/rtoslib.dir/Libraries/FreeRTOS/FreeRTOS/Source/tasks.c.i
.PHONY : Libraries/FreeRTOS/FreeRTOS/Source/tasks.c.i

Libraries/FreeRTOS/FreeRTOS/Source/tasks.s: Libraries/FreeRTOS/FreeRTOS/Source/tasks.c.s

.PHONY : Libraries/FreeRTOS/FreeRTOS/Source/tasks.s

# target to generate assembly for a file
Libraries/FreeRTOS/FreeRTOS/Source/tasks.c.s:
	$(MAKE) -f CMakeFiles/rtoslib.dir/build.make CMakeFiles/rtoslib.dir/Libraries/FreeRTOS/FreeRTOS/Source/tasks.c.s
.PHONY : Libraries/FreeRTOS/FreeRTOS/Source/tasks.c.s

Libraries/FreeRTOS/FreeRTOS/Source/timers.o: Libraries/FreeRTOS/FreeRTOS/Source/timers.c.o

.PHONY : Libraries/FreeRTOS/FreeRTOS/Source/timers.o

# target to build an object file
Libraries/FreeRTOS/FreeRTOS/Source/timers.c.o:
	$(MAKE) -f CMakeFiles/rtoslib.dir/build.make CMakeFiles/rtoslib.dir/Libraries/FreeRTOS/FreeRTOS/Source/timers.c.o
.PHONY : Libraries/FreeRTOS/FreeRTOS/Source/timers.c.o

Libraries/FreeRTOS/FreeRTOS/Source/timers.i: Libraries/FreeRTOS/FreeRTOS/Source/timers.c.i

.PHONY : Libraries/FreeRTOS/FreeRTOS/Source/timers.i

# target to preprocess a source file
Libraries/FreeRTOS/FreeRTOS/Source/timers.c.i:
	$(MAKE) -f CMakeFiles/rtoslib.dir/build.make CMakeFiles/rtoslib.dir/Libraries/FreeRTOS/FreeRTOS/Source/timers.c.i
.PHONY : Libraries/FreeRTOS/FreeRTOS/Source/timers.c.i

Libraries/FreeRTOS/FreeRTOS/Source/timers.s: Libraries/FreeRTOS/FreeRTOS/Source/timers.c.s

.PHONY : Libraries/FreeRTOS/FreeRTOS/Source/timers.s

# target to generate assembly for a file
Libraries/FreeRTOS/FreeRTOS/Source/timers.c.s:
	$(MAKE) -f CMakeFiles/rtoslib.dir/build.make CMakeFiles/rtoslib.dir/Libraries/FreeRTOS/FreeRTOS/Source/timers.c.s
.PHONY : Libraries/FreeRTOS/FreeRTOS/Source/timers.c.s

Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/misc.o: Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/misc.c.o

.PHONY : Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/misc.o

# target to build an object file
Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/misc.c.o:
	$(MAKE) -f CMakeFiles/stmperipheralslib.dir/build.make CMakeFiles/stmperipheralslib.dir/Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/misc.c.o
.PHONY : Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/misc.c.o

Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/misc.i: Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/misc.c.i

.PHONY : Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/misc.i

# target to preprocess a source file
Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/misc.c.i:
	$(MAKE) -f CMakeFiles/stmperipheralslib.dir/build.make CMakeFiles/stmperipheralslib.dir/Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/misc.c.i
.PHONY : Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/misc.c.i

Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/misc.s: Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/misc.c.s

.PHONY : Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/misc.s

# target to generate assembly for a file
Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/misc.c.s:
	$(MAKE) -f CMakeFiles/stmperipheralslib.dir/build.make CMakeFiles/stmperipheralslib.dir/Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/misc.c.s
.PHONY : Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/misc.c.s

Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_adc.o: Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_adc.c.o

.PHONY : Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_adc.o

# target to build an object file
Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_adc.c.o:
	$(MAKE) -f CMakeFiles/stmperipheralslib.dir/build.make CMakeFiles/stmperipheralslib.dir/Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_adc.c.o
.PHONY : Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_adc.c.o

Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_adc.i: Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_adc.c.i

.PHONY : Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_adc.i

# target to preprocess a source file
Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_adc.c.i:
	$(MAKE) -f CMakeFiles/stmperipheralslib.dir/build.make CMakeFiles/stmperipheralslib.dir/Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_adc.c.i
.PHONY : Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_adc.c.i

Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_adc.s: Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_adc.c.s

.PHONY : Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_adc.s

# target to generate assembly for a file
Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_adc.c.s:
	$(MAKE) -f CMakeFiles/stmperipheralslib.dir/build.make CMakeFiles/stmperipheralslib.dir/Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_adc.c.s
.PHONY : Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_adc.c.s

Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dma.o: Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dma.c.o

.PHONY : Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dma.o

# target to build an object file
Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dma.c.o:
	$(MAKE) -f CMakeFiles/stmperipheralslib.dir/build.make CMakeFiles/stmperipheralslib.dir/Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dma.c.o
.PHONY : Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dma.c.o

Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dma.i: Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dma.c.i

.PHONY : Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dma.i

# target to preprocess a source file
Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dma.c.i:
	$(MAKE) -f CMakeFiles/stmperipheralslib.dir/build.make CMakeFiles/stmperipheralslib.dir/Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dma.c.i
.PHONY : Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dma.c.i

Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dma.s: Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dma.c.s

.PHONY : Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dma.s

# target to generate assembly for a file
Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dma.c.s:
	$(MAKE) -f CMakeFiles/stmperipheralslib.dir/build.make CMakeFiles/stmperipheralslib.dir/Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dma.c.s
.PHONY : Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dma.c.s

Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dma2d.o: Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dma2d.c.o

.PHONY : Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dma2d.o

# target to build an object file
Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dma2d.c.o:
	$(MAKE) -f CMakeFiles/stmperipheralslib.dir/build.make CMakeFiles/stmperipheralslib.dir/Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dma2d.c.o
.PHONY : Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dma2d.c.o

Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dma2d.i: Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dma2d.c.i

.PHONY : Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dma2d.i

# target to preprocess a source file
Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dma2d.c.i:
	$(MAKE) -f CMakeFiles/stmperipheralslib.dir/build.make CMakeFiles/stmperipheralslib.dir/Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dma2d.c.i
.PHONY : Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dma2d.c.i

Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dma2d.s: Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dma2d.c.s

.PHONY : Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dma2d.s

# target to generate assembly for a file
Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dma2d.c.s:
	$(MAKE) -f CMakeFiles/stmperipheralslib.dir/build.make CMakeFiles/stmperipheralslib.dir/Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dma2d.c.s
.PHONY : Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dma2d.c.s

Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_exti.o: Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_exti.c.o

.PHONY : Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_exti.o

# target to build an object file
Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_exti.c.o:
	$(MAKE) -f CMakeFiles/stmperipheralslib.dir/build.make CMakeFiles/stmperipheralslib.dir/Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_exti.c.o
.PHONY : Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_exti.c.o

Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_exti.i: Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_exti.c.i

.PHONY : Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_exti.i

# target to preprocess a source file
Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_exti.c.i:
	$(MAKE) -f CMakeFiles/stmperipheralslib.dir/build.make CMakeFiles/stmperipheralslib.dir/Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_exti.c.i
.PHONY : Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_exti.c.i

Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_exti.s: Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_exti.c.s

.PHONY : Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_exti.s

# target to generate assembly for a file
Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_exti.c.s:
	$(MAKE) -f CMakeFiles/stmperipheralslib.dir/build.make CMakeFiles/stmperipheralslib.dir/Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_exti.c.s
.PHONY : Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_exti.c.s

Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_fmc.o: Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_fmc.c.o

.PHONY : Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_fmc.o

# target to build an object file
Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_fmc.c.o:
	$(MAKE) -f CMakeFiles/stmperipheralslib.dir/build.make CMakeFiles/stmperipheralslib.dir/Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_fmc.c.o
.PHONY : Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_fmc.c.o

Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_fmc.i: Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_fmc.c.i

.PHONY : Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_fmc.i

# target to preprocess a source file
Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_fmc.c.i:
	$(MAKE) -f CMakeFiles/stmperipheralslib.dir/build.make CMakeFiles/stmperipheralslib.dir/Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_fmc.c.i
.PHONY : Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_fmc.c.i

Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_fmc.s: Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_fmc.c.s

.PHONY : Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_fmc.s

# target to generate assembly for a file
Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_fmc.c.s:
	$(MAKE) -f CMakeFiles/stmperipheralslib.dir/build.make CMakeFiles/stmperipheralslib.dir/Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_fmc.c.s
.PHONY : Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_fmc.c.s

Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_gpio.o: Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_gpio.c.o

.PHONY : Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_gpio.o

# target to build an object file
Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_gpio.c.o:
	$(MAKE) -f CMakeFiles/stmperipheralslib.dir/build.make CMakeFiles/stmperipheralslib.dir/Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_gpio.c.o
.PHONY : Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_gpio.c.o

Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_gpio.i: Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_gpio.c.i

.PHONY : Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_gpio.i

# target to preprocess a source file
Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_gpio.c.i:
	$(MAKE) -f CMakeFiles/stmperipheralslib.dir/build.make CMakeFiles/stmperipheralslib.dir/Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_gpio.c.i
.PHONY : Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_gpio.c.i

Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_gpio.s: Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_gpio.c.s

.PHONY : Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_gpio.s

# target to generate assembly for a file
Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_gpio.c.s:
	$(MAKE) -f CMakeFiles/stmperipheralslib.dir/build.make CMakeFiles/stmperipheralslib.dir/Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_gpio.c.s
.PHONY : Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_gpio.c.s

Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_i2c.o: Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_i2c.c.o

.PHONY : Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_i2c.o

# target to build an object file
Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_i2c.c.o:
	$(MAKE) -f CMakeFiles/stmperipheralslib.dir/build.make CMakeFiles/stmperipheralslib.dir/Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_i2c.c.o
.PHONY : Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_i2c.c.o

Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_i2c.i: Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_i2c.c.i

.PHONY : Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_i2c.i

# target to preprocess a source file
Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_i2c.c.i:
	$(MAKE) -f CMakeFiles/stmperipheralslib.dir/build.make CMakeFiles/stmperipheralslib.dir/Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_i2c.c.i
.PHONY : Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_i2c.c.i

Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_i2c.s: Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_i2c.c.s

.PHONY : Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_i2c.s

# target to generate assembly for a file
Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_i2c.c.s:
	$(MAKE) -f CMakeFiles/stmperipheralslib.dir/build.make CMakeFiles/stmperipheralslib.dir/Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_i2c.c.s
.PHONY : Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_i2c.c.s

Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_ltdc.o: Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_ltdc.c.o

.PHONY : Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_ltdc.o

# target to build an object file
Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_ltdc.c.o:
	$(MAKE) -f CMakeFiles/stmperipheralslib.dir/build.make CMakeFiles/stmperipheralslib.dir/Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_ltdc.c.o
.PHONY : Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_ltdc.c.o

Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_ltdc.i: Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_ltdc.c.i

.PHONY : Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_ltdc.i

# target to preprocess a source file
Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_ltdc.c.i:
	$(MAKE) -f CMakeFiles/stmperipheralslib.dir/build.make CMakeFiles/stmperipheralslib.dir/Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_ltdc.c.i
.PHONY : Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_ltdc.c.i

Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_ltdc.s: Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_ltdc.c.s

.PHONY : Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_ltdc.s

# target to generate assembly for a file
Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_ltdc.c.s:
	$(MAKE) -f CMakeFiles/stmperipheralslib.dir/build.make CMakeFiles/stmperipheralslib.dir/Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_ltdc.c.s
.PHONY : Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_ltdc.c.s

Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rcc.o: Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rcc.c.o

.PHONY : Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rcc.o

# target to build an object file
Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rcc.c.o:
	$(MAKE) -f CMakeFiles/stmperipheralslib.dir/build.make CMakeFiles/stmperipheralslib.dir/Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rcc.c.o
.PHONY : Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rcc.c.o

Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rcc.i: Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rcc.c.i

.PHONY : Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rcc.i

# target to preprocess a source file
Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rcc.c.i:
	$(MAKE) -f CMakeFiles/stmperipheralslib.dir/build.make CMakeFiles/stmperipheralslib.dir/Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rcc.c.i
.PHONY : Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rcc.c.i

Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rcc.s: Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rcc.c.s

.PHONY : Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rcc.s

# target to generate assembly for a file
Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rcc.c.s:
	$(MAKE) -f CMakeFiles/stmperipheralslib.dir/build.make CMakeFiles/stmperipheralslib.dir/Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rcc.c.s
.PHONY : Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rcc.c.s

Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_spi.o: Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_spi.c.o

.PHONY : Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_spi.o

# target to build an object file
Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_spi.c.o:
	$(MAKE) -f CMakeFiles/stmperipheralslib.dir/build.make CMakeFiles/stmperipheralslib.dir/Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_spi.c.o
.PHONY : Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_spi.c.o

Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_spi.i: Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_spi.c.i

.PHONY : Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_spi.i

# target to preprocess a source file
Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_spi.c.i:
	$(MAKE) -f CMakeFiles/stmperipheralslib.dir/build.make CMakeFiles/stmperipheralslib.dir/Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_spi.c.i
.PHONY : Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_spi.c.i

Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_spi.s: Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_spi.c.s

.PHONY : Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_spi.s

# target to generate assembly for a file
Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_spi.c.s:
	$(MAKE) -f CMakeFiles/stmperipheralslib.dir/build.make CMakeFiles/stmperipheralslib.dir/Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_spi.c.s
.PHONY : Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_spi.c.s

Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_syscfg.o: Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_syscfg.c.o

.PHONY : Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_syscfg.o

# target to build an object file
Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_syscfg.c.o:
	$(MAKE) -f CMakeFiles/stmperipheralslib.dir/build.make CMakeFiles/stmperipheralslib.dir/Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_syscfg.c.o
.PHONY : Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_syscfg.c.o

Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_syscfg.i: Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_syscfg.c.i

.PHONY : Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_syscfg.i

# target to preprocess a source file
Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_syscfg.c.i:
	$(MAKE) -f CMakeFiles/stmperipheralslib.dir/build.make CMakeFiles/stmperipheralslib.dir/Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_syscfg.c.i
.PHONY : Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_syscfg.c.i

Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_syscfg.s: Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_syscfg.c.s

.PHONY : Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_syscfg.s

# target to generate assembly for a file
Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_syscfg.c.s:
	$(MAKE) -f CMakeFiles/stmperipheralslib.dir/build.make CMakeFiles/stmperipheralslib.dir/Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_syscfg.c.s
.PHONY : Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_syscfg.c.s

Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_tim.o: Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_tim.c.o

.PHONY : Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_tim.o

# target to build an object file
Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_tim.c.o:
	$(MAKE) -f CMakeFiles/stmperipheralslib.dir/build.make CMakeFiles/stmperipheralslib.dir/Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_tim.c.o
.PHONY : Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_tim.c.o

Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_tim.i: Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_tim.c.i

.PHONY : Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_tim.i

# target to preprocess a source file
Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_tim.c.i:
	$(MAKE) -f CMakeFiles/stmperipheralslib.dir/build.make CMakeFiles/stmperipheralslib.dir/Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_tim.c.i
.PHONY : Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_tim.c.i

Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_tim.s: Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_tim.c.s

.PHONY : Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_tim.s

# target to generate assembly for a file
Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_tim.c.s:
	$(MAKE) -f CMakeFiles/stmperipheralslib.dir/build.make CMakeFiles/stmperipheralslib.dir/Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_tim.c.s
.PHONY : Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_tim.c.s

Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_usart.o: Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_usart.c.o

.PHONY : Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_usart.o

# target to build an object file
Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_usart.c.o:
	$(MAKE) -f CMakeFiles/stmperipheralslib.dir/build.make CMakeFiles/stmperipheralslib.dir/Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_usart.c.o
.PHONY : Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_usart.c.o

Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_usart.i: Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_usart.c.i

.PHONY : Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_usart.i

# target to preprocess a source file
Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_usart.c.i:
	$(MAKE) -f CMakeFiles/stmperipheralslib.dir/build.make CMakeFiles/stmperipheralslib.dir/Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_usart.c.i
.PHONY : Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_usart.c.i

Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_usart.s: Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_usart.c.s

.PHONY : Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_usart.s

# target to generate assembly for a file
Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_usart.c.s:
	$(MAKE) -f CMakeFiles/stmperipheralslib.dir/build.make CMakeFiles/stmperipheralslib.dir/Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_usart.c.s
.PHONY : Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_usart.c.s

Libraries/STM32F4/Utilities/STM32_EVAL/STM32F429I-Discovery/stm32f429i_discovery_ioe.o: Libraries/STM32F4/Utilities/STM32_EVAL/STM32F429I-Discovery/stm32f429i_discovery_ioe.c.o

.PHONY : Libraries/STM32F4/Utilities/STM32_EVAL/STM32F429I-Discovery/stm32f429i_discovery_ioe.o

# target to build an object file
Libraries/STM32F4/Utilities/STM32_EVAL/STM32F429I-Discovery/stm32f429i_discovery_ioe.c.o:
	$(MAKE) -f CMakeFiles/stmutilitieslib.dir/build.make CMakeFiles/stmutilitieslib.dir/Libraries/STM32F4/Utilities/STM32_EVAL/STM32F429I-Discovery/stm32f429i_discovery_ioe.c.o
.PHONY : Libraries/STM32F4/Utilities/STM32_EVAL/STM32F429I-Discovery/stm32f429i_discovery_ioe.c.o

Libraries/STM32F4/Utilities/STM32_EVAL/STM32F429I-Discovery/stm32f429i_discovery_ioe.i: Libraries/STM32F4/Utilities/STM32_EVAL/STM32F429I-Discovery/stm32f429i_discovery_ioe.c.i

.PHONY : Libraries/STM32F4/Utilities/STM32_EVAL/STM32F429I-Discovery/stm32f429i_discovery_ioe.i

# target to preprocess a source file
Libraries/STM32F4/Utilities/STM32_EVAL/STM32F429I-Discovery/stm32f429i_discovery_ioe.c.i:
	$(MAKE) -f CMakeFiles/stmutilitieslib.dir/build.make CMakeFiles/stmutilitieslib.dir/Libraries/STM32F4/Utilities/STM32_EVAL/STM32F429I-Discovery/stm32f429i_discovery_ioe.c.i
.PHONY : Libraries/STM32F4/Utilities/STM32_EVAL/STM32F429I-Discovery/stm32f429i_discovery_ioe.c.i

Libraries/STM32F4/Utilities/STM32_EVAL/STM32F429I-Discovery/stm32f429i_discovery_ioe.s: Libraries/STM32F4/Utilities/STM32_EVAL/STM32F429I-Discovery/stm32f429i_discovery_ioe.c.s

.PHONY : Libraries/STM32F4/Utilities/STM32_EVAL/STM32F429I-Discovery/stm32f429i_discovery_ioe.s

# target to generate assembly for a file
Libraries/STM32F4/Utilities/STM32_EVAL/STM32F429I-Discovery/stm32f429i_discovery_ioe.c.s:
	$(MAKE) -f CMakeFiles/stmutilitieslib.dir/build.make CMakeFiles/stmutilitieslib.dir/Libraries/STM32F4/Utilities/STM32_EVAL/STM32F429I-Discovery/stm32f429i_discovery_ioe.c.s
.PHONY : Libraries/STM32F4/Utilities/STM32_EVAL/STM32F429I-Discovery/stm32f429i_discovery_ioe.c.s

Libraries/STM32F4/Utilities/STM32_EVAL/STM32F429I-Discovery/stm32f429i_discovery_lcd.o: Libraries/STM32F4/Utilities/STM32_EVAL/STM32F429I-Discovery/stm32f429i_discovery_lcd.c.o

.PHONY : Libraries/STM32F4/Utilities/STM32_EVAL/STM32F429I-Discovery/stm32f429i_discovery_lcd.o

# target to build an object file
Libraries/STM32F4/Utilities/STM32_EVAL/STM32F429I-Discovery/stm32f429i_discovery_lcd.c.o:
	$(MAKE) -f CMakeFiles/stmutilitieslib.dir/build.make CMakeFiles/stmutilitieslib.dir/Libraries/STM32F4/Utilities/STM32_EVAL/STM32F429I-Discovery/stm32f429i_discovery_lcd.c.o
.PHONY : Libraries/STM32F4/Utilities/STM32_EVAL/STM32F429I-Discovery/stm32f429i_discovery_lcd.c.o

Libraries/STM32F4/Utilities/STM32_EVAL/STM32F429I-Discovery/stm32f429i_discovery_lcd.i: Libraries/STM32F4/Utilities/STM32_EVAL/STM32F429I-Discovery/stm32f429i_discovery_lcd.c.i

.PHONY : Libraries/STM32F4/Utilities/STM32_EVAL/STM32F429I-Discovery/stm32f429i_discovery_lcd.i

# target to preprocess a source file
Libraries/STM32F4/Utilities/STM32_EVAL/STM32F429I-Discovery/stm32f429i_discovery_lcd.c.i:
	$(MAKE) -f CMakeFiles/stmutilitieslib.dir/build.make CMakeFiles/stmutilitieslib.dir/Libraries/STM32F4/Utilities/STM32_EVAL/STM32F429I-Discovery/stm32f429i_discovery_lcd.c.i
.PHONY : Libraries/STM32F4/Utilities/STM32_EVAL/STM32F429I-Discovery/stm32f429i_discovery_lcd.c.i

Libraries/STM32F4/Utilities/STM32_EVAL/STM32F429I-Discovery/stm32f429i_discovery_lcd.s: Libraries/STM32F4/Utilities/STM32_EVAL/STM32F429I-Discovery/stm32f429i_discovery_lcd.c.s

.PHONY : Libraries/STM32F4/Utilities/STM32_EVAL/STM32F429I-Discovery/stm32f429i_discovery_lcd.s

# target to generate assembly for a file
Libraries/STM32F4/Utilities/STM32_EVAL/STM32F429I-Discovery/stm32f429i_discovery_lcd.c.s:
	$(MAKE) -f CMakeFiles/stmutilitieslib.dir/build.make CMakeFiles/stmutilitieslib.dir/Libraries/STM32F4/Utilities/STM32_EVAL/STM32F429I-Discovery/stm32f429i_discovery_lcd.c.s
.PHONY : Libraries/STM32F4/Utilities/STM32_EVAL/STM32F429I-Discovery/stm32f429i_discovery_lcd.c.s

Libraries/STM32F4/Utilities/STM32_EVAL/STM32F429I-Discovery/stm32f429i_discovery_sdram.o: Libraries/STM32F4/Utilities/STM32_EVAL/STM32F429I-Discovery/stm32f429i_discovery_sdram.c.o

.PHONY : Libraries/STM32F4/Utilities/STM32_EVAL/STM32F429I-Discovery/stm32f429i_discovery_sdram.o

# target to build an object file
Libraries/STM32F4/Utilities/STM32_EVAL/STM32F429I-Discovery/stm32f429i_discovery_sdram.c.o:
	$(MAKE) -f CMakeFiles/stmutilitieslib.dir/build.make CMakeFiles/stmutilitieslib.dir/Libraries/STM32F4/Utilities/STM32_EVAL/STM32F429I-Discovery/stm32f429i_discovery_sdram.c.o
.PHONY : Libraries/STM32F4/Utilities/STM32_EVAL/STM32F429I-Discovery/stm32f429i_discovery_sdram.c.o

Libraries/STM32F4/Utilities/STM32_EVAL/STM32F429I-Discovery/stm32f429i_discovery_sdram.i: Libraries/STM32F4/Utilities/STM32_EVAL/STM32F429I-Discovery/stm32f429i_discovery_sdram.c.i

.PHONY : Libraries/STM32F4/Utilities/STM32_EVAL/STM32F429I-Discovery/stm32f429i_discovery_sdram.i

# target to preprocess a source file
Libraries/STM32F4/Utilities/STM32_EVAL/STM32F429I-Discovery/stm32f429i_discovery_sdram.c.i:
	$(MAKE) -f CMakeFiles/stmutilitieslib.dir/build.make CMakeFiles/stmutilitieslib.dir/Libraries/STM32F4/Utilities/STM32_EVAL/STM32F429I-Discovery/stm32f429i_discovery_sdram.c.i
.PHONY : Libraries/STM32F4/Utilities/STM32_EVAL/STM32F429I-Discovery/stm32f429i_discovery_sdram.c.i

Libraries/STM32F4/Utilities/STM32_EVAL/STM32F429I-Discovery/stm32f429i_discovery_sdram.s: Libraries/STM32F4/Utilities/STM32_EVAL/STM32F429I-Discovery/stm32f429i_discovery_sdram.c.s

.PHONY : Libraries/STM32F4/Utilities/STM32_EVAL/STM32F429I-Discovery/stm32f429i_discovery_sdram.s

# target to generate assembly for a file
Libraries/STM32F4/Utilities/STM32_EVAL/STM32F429I-Discovery/stm32f429i_discovery_sdram.c.s:
	$(MAKE) -f CMakeFiles/stmutilitieslib.dir/build.make CMakeFiles/stmutilitieslib.dir/Libraries/STM32F4/Utilities/STM32_EVAL/STM32F429I-Discovery/stm32f429i_discovery_sdram.c.s
.PHONY : Libraries/STM32F4/Utilities/STM32_EVAL/STM32F429I-Discovery/stm32f429i_discovery_sdram.c.s

Libraries/ugfx/src/gdisp/gdisp.o: Libraries/ugfx/src/gdisp/gdisp.c.o

.PHONY : Libraries/ugfx/src/gdisp/gdisp.o

# target to build an object file
Libraries/ugfx/src/gdisp/gdisp.c.o:
	$(MAKE) -f CMakeFiles/ugfxlib.dir/build.make CMakeFiles/ugfxlib.dir/Libraries/ugfx/src/gdisp/gdisp.c.o
.PHONY : Libraries/ugfx/src/gdisp/gdisp.c.o

Libraries/ugfx/src/gdisp/gdisp.i: Libraries/ugfx/src/gdisp/gdisp.c.i

.PHONY : Libraries/ugfx/src/gdisp/gdisp.i

# target to preprocess a source file
Libraries/ugfx/src/gdisp/gdisp.c.i:
	$(MAKE) -f CMakeFiles/ugfxlib.dir/build.make CMakeFiles/ugfxlib.dir/Libraries/ugfx/src/gdisp/gdisp.c.i
.PHONY : Libraries/ugfx/src/gdisp/gdisp.c.i

Libraries/ugfx/src/gdisp/gdisp.s: Libraries/ugfx/src/gdisp/gdisp.c.s

.PHONY : Libraries/ugfx/src/gdisp/gdisp.s

# target to generate assembly for a file
Libraries/ugfx/src/gdisp/gdisp.c.s:
	$(MAKE) -f CMakeFiles/ugfxlib.dir/build.make CMakeFiles/ugfxlib.dir/Libraries/ugfx/src/gdisp/gdisp.c.s
.PHONY : Libraries/ugfx/src/gdisp/gdisp.c.s

Libraries/ugfx/src/gdisp/gdisp_fonts.o: Libraries/ugfx/src/gdisp/gdisp_fonts.c.o

.PHONY : Libraries/ugfx/src/gdisp/gdisp_fonts.o

# target to build an object file
Libraries/ugfx/src/gdisp/gdisp_fonts.c.o:
	$(MAKE) -f CMakeFiles/ugfxlib.dir/build.make CMakeFiles/ugfxlib.dir/Libraries/ugfx/src/gdisp/gdisp_fonts.c.o
.PHONY : Libraries/ugfx/src/gdisp/gdisp_fonts.c.o

Libraries/ugfx/src/gdisp/gdisp_fonts.i: Libraries/ugfx/src/gdisp/gdisp_fonts.c.i

.PHONY : Libraries/ugfx/src/gdisp/gdisp_fonts.i

# target to preprocess a source file
Libraries/ugfx/src/gdisp/gdisp_fonts.c.i:
	$(MAKE) -f CMakeFiles/ugfxlib.dir/build.make CMakeFiles/ugfxlib.dir/Libraries/ugfx/src/gdisp/gdisp_fonts.c.i
.PHONY : Libraries/ugfx/src/gdisp/gdisp_fonts.c.i

Libraries/ugfx/src/gdisp/gdisp_fonts.s: Libraries/ugfx/src/gdisp/gdisp_fonts.c.s

.PHONY : Libraries/ugfx/src/gdisp/gdisp_fonts.s

# target to generate assembly for a file
Libraries/ugfx/src/gdisp/gdisp_fonts.c.s:
	$(MAKE) -f CMakeFiles/ugfxlib.dir/build.make CMakeFiles/ugfxlib.dir/Libraries/ugfx/src/gdisp/gdisp_fonts.c.s
.PHONY : Libraries/ugfx/src/gdisp/gdisp_fonts.c.s

Libraries/ugfx/src/gdisp/mcufont/mf_encoding.o: Libraries/ugfx/src/gdisp/mcufont/mf_encoding.c.o

.PHONY : Libraries/ugfx/src/gdisp/mcufont/mf_encoding.o

# target to build an object file
Libraries/ugfx/src/gdisp/mcufont/mf_encoding.c.o:
	$(MAKE) -f CMakeFiles/ugfxlib.dir/build.make CMakeFiles/ugfxlib.dir/Libraries/ugfx/src/gdisp/mcufont/mf_encoding.c.o
.PHONY : Libraries/ugfx/src/gdisp/mcufont/mf_encoding.c.o

Libraries/ugfx/src/gdisp/mcufont/mf_encoding.i: Libraries/ugfx/src/gdisp/mcufont/mf_encoding.c.i

.PHONY : Libraries/ugfx/src/gdisp/mcufont/mf_encoding.i

# target to preprocess a source file
Libraries/ugfx/src/gdisp/mcufont/mf_encoding.c.i:
	$(MAKE) -f CMakeFiles/ugfxlib.dir/build.make CMakeFiles/ugfxlib.dir/Libraries/ugfx/src/gdisp/mcufont/mf_encoding.c.i
.PHONY : Libraries/ugfx/src/gdisp/mcufont/mf_encoding.c.i

Libraries/ugfx/src/gdisp/mcufont/mf_encoding.s: Libraries/ugfx/src/gdisp/mcufont/mf_encoding.c.s

.PHONY : Libraries/ugfx/src/gdisp/mcufont/mf_encoding.s

# target to generate assembly for a file
Libraries/ugfx/src/gdisp/mcufont/mf_encoding.c.s:
	$(MAKE) -f CMakeFiles/ugfxlib.dir/build.make CMakeFiles/ugfxlib.dir/Libraries/ugfx/src/gdisp/mcufont/mf_encoding.c.s
.PHONY : Libraries/ugfx/src/gdisp/mcufont/mf_encoding.c.s

Libraries/ugfx/src/gdisp/mcufont/mf_font.o: Libraries/ugfx/src/gdisp/mcufont/mf_font.c.o

.PHONY : Libraries/ugfx/src/gdisp/mcufont/mf_font.o

# target to build an object file
Libraries/ugfx/src/gdisp/mcufont/mf_font.c.o:
	$(MAKE) -f CMakeFiles/ugfxlib.dir/build.make CMakeFiles/ugfxlib.dir/Libraries/ugfx/src/gdisp/mcufont/mf_font.c.o
.PHONY : Libraries/ugfx/src/gdisp/mcufont/mf_font.c.o

Libraries/ugfx/src/gdisp/mcufont/mf_font.i: Libraries/ugfx/src/gdisp/mcufont/mf_font.c.i

.PHONY : Libraries/ugfx/src/gdisp/mcufont/mf_font.i

# target to preprocess a source file
Libraries/ugfx/src/gdisp/mcufont/mf_font.c.i:
	$(MAKE) -f CMakeFiles/ugfxlib.dir/build.make CMakeFiles/ugfxlib.dir/Libraries/ugfx/src/gdisp/mcufont/mf_font.c.i
.PHONY : Libraries/ugfx/src/gdisp/mcufont/mf_font.c.i

Libraries/ugfx/src/gdisp/mcufont/mf_font.s: Libraries/ugfx/src/gdisp/mcufont/mf_font.c.s

.PHONY : Libraries/ugfx/src/gdisp/mcufont/mf_font.s

# target to generate assembly for a file
Libraries/ugfx/src/gdisp/mcufont/mf_font.c.s:
	$(MAKE) -f CMakeFiles/ugfxlib.dir/build.make CMakeFiles/ugfxlib.dir/Libraries/ugfx/src/gdisp/mcufont/mf_font.c.s
.PHONY : Libraries/ugfx/src/gdisp/mcufont/mf_font.c.s

Libraries/ugfx/src/gdisp/mcufont/mf_justify.o: Libraries/ugfx/src/gdisp/mcufont/mf_justify.c.o

.PHONY : Libraries/ugfx/src/gdisp/mcufont/mf_justify.o

# target to build an object file
Libraries/ugfx/src/gdisp/mcufont/mf_justify.c.o:
	$(MAKE) -f CMakeFiles/ugfxlib.dir/build.make CMakeFiles/ugfxlib.dir/Libraries/ugfx/src/gdisp/mcufont/mf_justify.c.o
.PHONY : Libraries/ugfx/src/gdisp/mcufont/mf_justify.c.o

Libraries/ugfx/src/gdisp/mcufont/mf_justify.i: Libraries/ugfx/src/gdisp/mcufont/mf_justify.c.i

.PHONY : Libraries/ugfx/src/gdisp/mcufont/mf_justify.i

# target to preprocess a source file
Libraries/ugfx/src/gdisp/mcufont/mf_justify.c.i:
	$(MAKE) -f CMakeFiles/ugfxlib.dir/build.make CMakeFiles/ugfxlib.dir/Libraries/ugfx/src/gdisp/mcufont/mf_justify.c.i
.PHONY : Libraries/ugfx/src/gdisp/mcufont/mf_justify.c.i

Libraries/ugfx/src/gdisp/mcufont/mf_justify.s: Libraries/ugfx/src/gdisp/mcufont/mf_justify.c.s

.PHONY : Libraries/ugfx/src/gdisp/mcufont/mf_justify.s

# target to generate assembly for a file
Libraries/ugfx/src/gdisp/mcufont/mf_justify.c.s:
	$(MAKE) -f CMakeFiles/ugfxlib.dir/build.make CMakeFiles/ugfxlib.dir/Libraries/ugfx/src/gdisp/mcufont/mf_justify.c.s
.PHONY : Libraries/ugfx/src/gdisp/mcufont/mf_justify.c.s

Libraries/ugfx/src/gdisp/mcufont/mf_rlefont.o: Libraries/ugfx/src/gdisp/mcufont/mf_rlefont.c.o

.PHONY : Libraries/ugfx/src/gdisp/mcufont/mf_rlefont.o

# target to build an object file
Libraries/ugfx/src/gdisp/mcufont/mf_rlefont.c.o:
	$(MAKE) -f CMakeFiles/ugfxlib.dir/build.make CMakeFiles/ugfxlib.dir/Libraries/ugfx/src/gdisp/mcufont/mf_rlefont.c.o
.PHONY : Libraries/ugfx/src/gdisp/mcufont/mf_rlefont.c.o

Libraries/ugfx/src/gdisp/mcufont/mf_rlefont.i: Libraries/ugfx/src/gdisp/mcufont/mf_rlefont.c.i

.PHONY : Libraries/ugfx/src/gdisp/mcufont/mf_rlefont.i

# target to preprocess a source file
Libraries/ugfx/src/gdisp/mcufont/mf_rlefont.c.i:
	$(MAKE) -f CMakeFiles/ugfxlib.dir/build.make CMakeFiles/ugfxlib.dir/Libraries/ugfx/src/gdisp/mcufont/mf_rlefont.c.i
.PHONY : Libraries/ugfx/src/gdisp/mcufont/mf_rlefont.c.i

Libraries/ugfx/src/gdisp/mcufont/mf_rlefont.s: Libraries/ugfx/src/gdisp/mcufont/mf_rlefont.c.s

.PHONY : Libraries/ugfx/src/gdisp/mcufont/mf_rlefont.s

# target to generate assembly for a file
Libraries/ugfx/src/gdisp/mcufont/mf_rlefont.c.s:
	$(MAKE) -f CMakeFiles/ugfxlib.dir/build.make CMakeFiles/ugfxlib.dir/Libraries/ugfx/src/gdisp/mcufont/mf_rlefont.c.s
.PHONY : Libraries/ugfx/src/gdisp/mcufont/mf_rlefont.c.s

Libraries/ugfx/src/gdisp/mcufont/mf_scaledfont.o: Libraries/ugfx/src/gdisp/mcufont/mf_scaledfont.c.o

.PHONY : Libraries/ugfx/src/gdisp/mcufont/mf_scaledfont.o

# target to build an object file
Libraries/ugfx/src/gdisp/mcufont/mf_scaledfont.c.o:
	$(MAKE) -f CMakeFiles/ugfxlib.dir/build.make CMakeFiles/ugfxlib.dir/Libraries/ugfx/src/gdisp/mcufont/mf_scaledfont.c.o
.PHONY : Libraries/ugfx/src/gdisp/mcufont/mf_scaledfont.c.o

Libraries/ugfx/src/gdisp/mcufont/mf_scaledfont.i: Libraries/ugfx/src/gdisp/mcufont/mf_scaledfont.c.i

.PHONY : Libraries/ugfx/src/gdisp/mcufont/mf_scaledfont.i

# target to preprocess a source file
Libraries/ugfx/src/gdisp/mcufont/mf_scaledfont.c.i:
	$(MAKE) -f CMakeFiles/ugfxlib.dir/build.make CMakeFiles/ugfxlib.dir/Libraries/ugfx/src/gdisp/mcufont/mf_scaledfont.c.i
.PHONY : Libraries/ugfx/src/gdisp/mcufont/mf_scaledfont.c.i

Libraries/ugfx/src/gdisp/mcufont/mf_scaledfont.s: Libraries/ugfx/src/gdisp/mcufont/mf_scaledfont.c.s

.PHONY : Libraries/ugfx/src/gdisp/mcufont/mf_scaledfont.s

# target to generate assembly for a file
Libraries/ugfx/src/gdisp/mcufont/mf_scaledfont.c.s:
	$(MAKE) -f CMakeFiles/ugfxlib.dir/build.make CMakeFiles/ugfxlib.dir/Libraries/ugfx/src/gdisp/mcufont/mf_scaledfont.c.s
.PHONY : Libraries/ugfx/src/gdisp/mcufont/mf_scaledfont.c.s

Libraries/ugfx/src/gdriver/gdriver.o: Libraries/ugfx/src/gdriver/gdriver.c.o

.PHONY : Libraries/ugfx/src/gdriver/gdriver.o

# target to build an object file
Libraries/ugfx/src/gdriver/gdriver.c.o:
	$(MAKE) -f CMakeFiles/ugfxlib.dir/build.make CMakeFiles/ugfxlib.dir/Libraries/ugfx/src/gdriver/gdriver.c.o
.PHONY : Libraries/ugfx/src/gdriver/gdriver.c.o

Libraries/ugfx/src/gdriver/gdriver.i: Libraries/ugfx/src/gdriver/gdriver.c.i

.PHONY : Libraries/ugfx/src/gdriver/gdriver.i

# target to preprocess a source file
Libraries/ugfx/src/gdriver/gdriver.c.i:
	$(MAKE) -f CMakeFiles/ugfxlib.dir/build.make CMakeFiles/ugfxlib.dir/Libraries/ugfx/src/gdriver/gdriver.c.i
.PHONY : Libraries/ugfx/src/gdriver/gdriver.c.i

Libraries/ugfx/src/gdriver/gdriver.s: Libraries/ugfx/src/gdriver/gdriver.c.s

.PHONY : Libraries/ugfx/src/gdriver/gdriver.s

# target to generate assembly for a file
Libraries/ugfx/src/gdriver/gdriver.c.s:
	$(MAKE) -f CMakeFiles/ugfxlib.dir/build.make CMakeFiles/ugfxlib.dir/Libraries/ugfx/src/gdriver/gdriver.c.s
.PHONY : Libraries/ugfx/src/gdriver/gdriver.c.s

Libraries/ugfx/src/gevent/gevent.o: Libraries/ugfx/src/gevent/gevent.c.o

.PHONY : Libraries/ugfx/src/gevent/gevent.o

# target to build an object file
Libraries/ugfx/src/gevent/gevent.c.o:
	$(MAKE) -f CMakeFiles/ugfxlib.dir/build.make CMakeFiles/ugfxlib.dir/Libraries/ugfx/src/gevent/gevent.c.o
.PHONY : Libraries/ugfx/src/gevent/gevent.c.o

Libraries/ugfx/src/gevent/gevent.i: Libraries/ugfx/src/gevent/gevent.c.i

.PHONY : Libraries/ugfx/src/gevent/gevent.i

# target to preprocess a source file
Libraries/ugfx/src/gevent/gevent.c.i:
	$(MAKE) -f CMakeFiles/ugfxlib.dir/build.make CMakeFiles/ugfxlib.dir/Libraries/ugfx/src/gevent/gevent.c.i
.PHONY : Libraries/ugfx/src/gevent/gevent.c.i

Libraries/ugfx/src/gevent/gevent.s: Libraries/ugfx/src/gevent/gevent.c.s

.PHONY : Libraries/ugfx/src/gevent/gevent.s

# target to generate assembly for a file
Libraries/ugfx/src/gevent/gevent.c.s:
	$(MAKE) -f CMakeFiles/ugfxlib.dir/build.make CMakeFiles/ugfxlib.dir/Libraries/ugfx/src/gevent/gevent.c.s
.PHONY : Libraries/ugfx/src/gevent/gevent.c.s

Libraries/ugfx/src/gfx.o: Libraries/ugfx/src/gfx.c.o

.PHONY : Libraries/ugfx/src/gfx.o

# target to build an object file
Libraries/ugfx/src/gfx.c.o:
	$(MAKE) -f CMakeFiles/ugfxlib.dir/build.make CMakeFiles/ugfxlib.dir/Libraries/ugfx/src/gfx.c.o
.PHONY : Libraries/ugfx/src/gfx.c.o

Libraries/ugfx/src/gfx.i: Libraries/ugfx/src/gfx.c.i

.PHONY : Libraries/ugfx/src/gfx.i

# target to preprocess a source file
Libraries/ugfx/src/gfx.c.i:
	$(MAKE) -f CMakeFiles/ugfxlib.dir/build.make CMakeFiles/ugfxlib.dir/Libraries/ugfx/src/gfx.c.i
.PHONY : Libraries/ugfx/src/gfx.c.i

Libraries/ugfx/src/gfx.s: Libraries/ugfx/src/gfx.c.s

.PHONY : Libraries/ugfx/src/gfx.s

# target to generate assembly for a file
Libraries/ugfx/src/gfx.c.s:
	$(MAKE) -f CMakeFiles/ugfxlib.dir/build.make CMakeFiles/ugfxlib.dir/Libraries/ugfx/src/gfx.c.s
.PHONY : Libraries/ugfx/src/gfx.c.s

Libraries/ugfx/src/ginput/ginput.o: Libraries/ugfx/src/ginput/ginput.c.o

.PHONY : Libraries/ugfx/src/ginput/ginput.o

# target to build an object file
Libraries/ugfx/src/ginput/ginput.c.o:
	$(MAKE) -f CMakeFiles/ugfxlib.dir/build.make CMakeFiles/ugfxlib.dir/Libraries/ugfx/src/ginput/ginput.c.o
.PHONY : Libraries/ugfx/src/ginput/ginput.c.o

Libraries/ugfx/src/ginput/ginput.i: Libraries/ugfx/src/ginput/ginput.c.i

.PHONY : Libraries/ugfx/src/ginput/ginput.i

# target to preprocess a source file
Libraries/ugfx/src/ginput/ginput.c.i:
	$(MAKE) -f CMakeFiles/ugfxlib.dir/build.make CMakeFiles/ugfxlib.dir/Libraries/ugfx/src/ginput/ginput.c.i
.PHONY : Libraries/ugfx/src/ginput/ginput.c.i

Libraries/ugfx/src/ginput/ginput.s: Libraries/ugfx/src/ginput/ginput.c.s

.PHONY : Libraries/ugfx/src/ginput/ginput.s

# target to generate assembly for a file
Libraries/ugfx/src/ginput/ginput.c.s:
	$(MAKE) -f CMakeFiles/ugfxlib.dir/build.make CMakeFiles/ugfxlib.dir/Libraries/ugfx/src/ginput/ginput.c.s
.PHONY : Libraries/ugfx/src/ginput/ginput.c.s

Libraries/ugfx/src/ginput/ginput_mouse.o: Libraries/ugfx/src/ginput/ginput_mouse.c.o

.PHONY : Libraries/ugfx/src/ginput/ginput_mouse.o

# target to build an object file
Libraries/ugfx/src/ginput/ginput_mouse.c.o:
	$(MAKE) -f CMakeFiles/ugfxlib.dir/build.make CMakeFiles/ugfxlib.dir/Libraries/ugfx/src/ginput/ginput_mouse.c.o
.PHONY : Libraries/ugfx/src/ginput/ginput_mouse.c.o

Libraries/ugfx/src/ginput/ginput_mouse.i: Libraries/ugfx/src/ginput/ginput_mouse.c.i

.PHONY : Libraries/ugfx/src/ginput/ginput_mouse.i

# target to preprocess a source file
Libraries/ugfx/src/ginput/ginput_mouse.c.i:
	$(MAKE) -f CMakeFiles/ugfxlib.dir/build.make CMakeFiles/ugfxlib.dir/Libraries/ugfx/src/ginput/ginput_mouse.c.i
.PHONY : Libraries/ugfx/src/ginput/ginput_mouse.c.i

Libraries/ugfx/src/ginput/ginput_mouse.s: Libraries/ugfx/src/ginput/ginput_mouse.c.s

.PHONY : Libraries/ugfx/src/ginput/ginput_mouse.s

# target to generate assembly for a file
Libraries/ugfx/src/ginput/ginput_mouse.c.s:
	$(MAKE) -f CMakeFiles/ugfxlib.dir/build.make CMakeFiles/ugfxlib.dir/Libraries/ugfx/src/ginput/ginput_mouse.c.s
.PHONY : Libraries/ugfx/src/ginput/ginput_mouse.c.s

Libraries/ugfx/src/gos/gos_freertos.o: Libraries/ugfx/src/gos/gos_freertos.c.o

.PHONY : Libraries/ugfx/src/gos/gos_freertos.o

# target to build an object file
Libraries/ugfx/src/gos/gos_freertos.c.o:
	$(MAKE) -f CMakeFiles/ugfxlib.dir/build.make CMakeFiles/ugfxlib.dir/Libraries/ugfx/src/gos/gos_freertos.c.o
.PHONY : Libraries/ugfx/src/gos/gos_freertos.c.o

Libraries/ugfx/src/gos/gos_freertos.i: Libraries/ugfx/src/gos/gos_freertos.c.i

.PHONY : Libraries/ugfx/src/gos/gos_freertos.i

# target to preprocess a source file
Libraries/ugfx/src/gos/gos_freertos.c.i:
	$(MAKE) -f CMakeFiles/ugfxlib.dir/build.make CMakeFiles/ugfxlib.dir/Libraries/ugfx/src/gos/gos_freertos.c.i
.PHONY : Libraries/ugfx/src/gos/gos_freertos.c.i

Libraries/ugfx/src/gos/gos_freertos.s: Libraries/ugfx/src/gos/gos_freertos.c.s

.PHONY : Libraries/ugfx/src/gos/gos_freertos.s

# target to generate assembly for a file
Libraries/ugfx/src/gos/gos_freertos.c.s:
	$(MAKE) -f CMakeFiles/ugfxlib.dir/build.make CMakeFiles/ugfxlib.dir/Libraries/ugfx/src/gos/gos_freertos.c.s
.PHONY : Libraries/ugfx/src/gos/gos_freertos.c.s

Libraries/ugfx/src/gtimer/gtimer.o: Libraries/ugfx/src/gtimer/gtimer.c.o

.PHONY : Libraries/ugfx/src/gtimer/gtimer.o

# target to build an object file
Libraries/ugfx/src/gtimer/gtimer.c.o:
	$(MAKE) -f CMakeFiles/ugfxlib.dir/build.make CMakeFiles/ugfxlib.dir/Libraries/ugfx/src/gtimer/gtimer.c.o
.PHONY : Libraries/ugfx/src/gtimer/gtimer.c.o

Libraries/ugfx/src/gtimer/gtimer.i: Libraries/ugfx/src/gtimer/gtimer.c.i

.PHONY : Libraries/ugfx/src/gtimer/gtimer.i

# target to preprocess a source file
Libraries/ugfx/src/gtimer/gtimer.c.i:
	$(MAKE) -f CMakeFiles/ugfxlib.dir/build.make CMakeFiles/ugfxlib.dir/Libraries/ugfx/src/gtimer/gtimer.c.i
.PHONY : Libraries/ugfx/src/gtimer/gtimer.c.i

Libraries/ugfx/src/gtimer/gtimer.s: Libraries/ugfx/src/gtimer/gtimer.c.s

.PHONY : Libraries/ugfx/src/gtimer/gtimer.s

# target to generate assembly for a file
Libraries/ugfx/src/gtimer/gtimer.c.s:
	$(MAKE) -f CMakeFiles/ugfxlib.dir/build.make CMakeFiles/ugfxlib.dir/Libraries/ugfx/src/gtimer/gtimer.c.s
.PHONY : Libraries/ugfx/src/gtimer/gtimer.c.s

Libraries/ugfx/src/gwin/gwin.o: Libraries/ugfx/src/gwin/gwin.c.o

.PHONY : Libraries/ugfx/src/gwin/gwin.o

# target to build an object file
Libraries/ugfx/src/gwin/gwin.c.o:
	$(MAKE) -f CMakeFiles/ugfxlib.dir/build.make CMakeFiles/ugfxlib.dir/Libraries/ugfx/src/gwin/gwin.c.o
.PHONY : Libraries/ugfx/src/gwin/gwin.c.o

Libraries/ugfx/src/gwin/gwin.i: Libraries/ugfx/src/gwin/gwin.c.i

.PHONY : Libraries/ugfx/src/gwin/gwin.i

# target to preprocess a source file
Libraries/ugfx/src/gwin/gwin.c.i:
	$(MAKE) -f CMakeFiles/ugfxlib.dir/build.make CMakeFiles/ugfxlib.dir/Libraries/ugfx/src/gwin/gwin.c.i
.PHONY : Libraries/ugfx/src/gwin/gwin.c.i

Libraries/ugfx/src/gwin/gwin.s: Libraries/ugfx/src/gwin/gwin.c.s

.PHONY : Libraries/ugfx/src/gwin/gwin.s

# target to generate assembly for a file
Libraries/ugfx/src/gwin/gwin.c.s:
	$(MAKE) -f CMakeFiles/ugfxlib.dir/build.make CMakeFiles/ugfxlib.dir/Libraries/ugfx/src/gwin/gwin.c.s
.PHONY : Libraries/ugfx/src/gwin/gwin.c.s

Libraries/ugfx/src/gwin/gwin_console.o: Libraries/ugfx/src/gwin/gwin_console.c.o

.PHONY : Libraries/ugfx/src/gwin/gwin_console.o

# target to build an object file
Libraries/ugfx/src/gwin/gwin_console.c.o:
	$(MAKE) -f CMakeFiles/ugfxlib.dir/build.make CMakeFiles/ugfxlib.dir/Libraries/ugfx/src/gwin/gwin_console.c.o
.PHONY : Libraries/ugfx/src/gwin/gwin_console.c.o

Libraries/ugfx/src/gwin/gwin_console.i: Libraries/ugfx/src/gwin/gwin_console.c.i

.PHONY : Libraries/ugfx/src/gwin/gwin_console.i

# target to preprocess a source file
Libraries/ugfx/src/gwin/gwin_console.c.i:
	$(MAKE) -f CMakeFiles/ugfxlib.dir/build.make CMakeFiles/ugfxlib.dir/Libraries/ugfx/src/gwin/gwin_console.c.i
.PHONY : Libraries/ugfx/src/gwin/gwin_console.c.i

Libraries/ugfx/src/gwin/gwin_console.s: Libraries/ugfx/src/gwin/gwin_console.c.s

.PHONY : Libraries/ugfx/src/gwin/gwin_console.s

# target to generate assembly for a file
Libraries/ugfx/src/gwin/gwin_console.c.s:
	$(MAKE) -f CMakeFiles/ugfxlib.dir/build.make CMakeFiles/ugfxlib.dir/Libraries/ugfx/src/gwin/gwin_console.c.s
.PHONY : Libraries/ugfx/src/gwin/gwin_console.c.s

Libraries/ugfx/src/gwin/gwin_wm.o: Libraries/ugfx/src/gwin/gwin_wm.c.o

.PHONY : Libraries/ugfx/src/gwin/gwin_wm.o

# target to build an object file
Libraries/ugfx/src/gwin/gwin_wm.c.o:
	$(MAKE) -f CMakeFiles/ugfxlib.dir/build.make CMakeFiles/ugfxlib.dir/Libraries/ugfx/src/gwin/gwin_wm.c.o
.PHONY : Libraries/ugfx/src/gwin/gwin_wm.c.o

Libraries/ugfx/src/gwin/gwin_wm.i: Libraries/ugfx/src/gwin/gwin_wm.c.i

.PHONY : Libraries/ugfx/src/gwin/gwin_wm.i

# target to preprocess a source file
Libraries/ugfx/src/gwin/gwin_wm.c.i:
	$(MAKE) -f CMakeFiles/ugfxlib.dir/build.make CMakeFiles/ugfxlib.dir/Libraries/ugfx/src/gwin/gwin_wm.c.i
.PHONY : Libraries/ugfx/src/gwin/gwin_wm.c.i

Libraries/ugfx/src/gwin/gwin_wm.s: Libraries/ugfx/src/gwin/gwin_wm.c.s

.PHONY : Libraries/ugfx/src/gwin/gwin_wm.s

# target to generate assembly for a file
Libraries/ugfx/src/gwin/gwin_wm.c.s:
	$(MAKE) -f CMakeFiles/ugfxlib.dir/build.make CMakeFiles/ugfxlib.dir/Libraries/ugfx/src/gwin/gwin_wm.c.s
.PHONY : Libraries/ugfx/src/gwin/gwin_wm.c.s

Libraries/usr/ESPL_functions.o: Libraries/usr/ESPL_functions.c.o

.PHONY : Libraries/usr/ESPL_functions.o

# target to build an object file
Libraries/usr/ESPL_functions.c.o:
	$(MAKE) -f CMakeFiles/usrlib.dir/build.make CMakeFiles/usrlib.dir/Libraries/usr/ESPL_functions.c.o
.PHONY : Libraries/usr/ESPL_functions.c.o

Libraries/usr/ESPL_functions.i: Libraries/usr/ESPL_functions.c.i

.PHONY : Libraries/usr/ESPL_functions.i

# target to preprocess a source file
Libraries/usr/ESPL_functions.c.i:
	$(MAKE) -f CMakeFiles/usrlib.dir/build.make CMakeFiles/usrlib.dir/Libraries/usr/ESPL_functions.c.i
.PHONY : Libraries/usr/ESPL_functions.c.i

Libraries/usr/ESPL_functions.s: Libraries/usr/ESPL_functions.c.s

.PHONY : Libraries/usr/ESPL_functions.s

# target to generate assembly for a file
Libraries/usr/ESPL_functions.c.s:
	$(MAKE) -f CMakeFiles/usrlib.dir/build.make CMakeFiles/usrlib.dir/Libraries/usr/ESPL_functions.c.s
.PHONY : Libraries/usr/ESPL_functions.c.s

Libraries/usr/ParTest.o: Libraries/usr/ParTest.c.o

.PHONY : Libraries/usr/ParTest.o

# target to build an object file
Libraries/usr/ParTest.c.o:
	$(MAKE) -f CMakeFiles/usrlib.dir/build.make CMakeFiles/usrlib.dir/Libraries/usr/ParTest.c.o
.PHONY : Libraries/usr/ParTest.c.o

Libraries/usr/ParTest.i: Libraries/usr/ParTest.c.i

.PHONY : Libraries/usr/ParTest.i

# target to preprocess a source file
Libraries/usr/ParTest.c.i:
	$(MAKE) -f CMakeFiles/usrlib.dir/build.make CMakeFiles/usrlib.dir/Libraries/usr/ParTest.c.i
.PHONY : Libraries/usr/ParTest.c.i

Libraries/usr/ParTest.s: Libraries/usr/ParTest.c.s

.PHONY : Libraries/usr/ParTest.s

# target to generate assembly for a file
Libraries/usr/ParTest.c.s:
	$(MAKE) -f CMakeFiles/usrlib.dir/build.make CMakeFiles/usrlib.dir/Libraries/usr/ParTest.c.s
.PHONY : Libraries/usr/ParTest.c.s

Libraries/usr/gdisp_lld_ILI9341.o: Libraries/usr/gdisp_lld_ILI9341.c.o

.PHONY : Libraries/usr/gdisp_lld_ILI9341.o

# target to build an object file
Libraries/usr/gdisp_lld_ILI9341.c.o:
	$(MAKE) -f CMakeFiles/usrlib.dir/build.make CMakeFiles/usrlib.dir/Libraries/usr/gdisp_lld_ILI9341.c.o
.PHONY : Libraries/usr/gdisp_lld_ILI9341.c.o

Libraries/usr/gdisp_lld_ILI9341.i: Libraries/usr/gdisp_lld_ILI9341.c.i

.PHONY : Libraries/usr/gdisp_lld_ILI9341.i

# target to preprocess a source file
Libraries/usr/gdisp_lld_ILI9341.c.i:
	$(MAKE) -f CMakeFiles/usrlib.dir/build.make CMakeFiles/usrlib.dir/Libraries/usr/gdisp_lld_ILI9341.c.i
.PHONY : Libraries/usr/gdisp_lld_ILI9341.c.i

Libraries/usr/gdisp_lld_ILI9341.s: Libraries/usr/gdisp_lld_ILI9341.c.s

.PHONY : Libraries/usr/gdisp_lld_ILI9341.s

# target to generate assembly for a file
Libraries/usr/gdisp_lld_ILI9341.c.s:
	$(MAKE) -f CMakeFiles/usrlib.dir/build.make CMakeFiles/usrlib.dir/Libraries/usr/gdisp_lld_ILI9341.c.s
.PHONY : Libraries/usr/gdisp_lld_ILI9341.c.s

Libraries/usr/ginput_lld_mouse.o: Libraries/usr/ginput_lld_mouse.c.o

.PHONY : Libraries/usr/ginput_lld_mouse.o

# target to build an object file
Libraries/usr/ginput_lld_mouse.c.o:
	$(MAKE) -f CMakeFiles/usrlib.dir/build.make CMakeFiles/usrlib.dir/Libraries/usr/ginput_lld_mouse.c.o
.PHONY : Libraries/usr/ginput_lld_mouse.c.o

Libraries/usr/ginput_lld_mouse.i: Libraries/usr/ginput_lld_mouse.c.i

.PHONY : Libraries/usr/ginput_lld_mouse.i

# target to preprocess a source file
Libraries/usr/ginput_lld_mouse.c.i:
	$(MAKE) -f CMakeFiles/usrlib.dir/build.make CMakeFiles/usrlib.dir/Libraries/usr/ginput_lld_mouse.c.i
.PHONY : Libraries/usr/ginput_lld_mouse.c.i

Libraries/usr/ginput_lld_mouse.s: Libraries/usr/ginput_lld_mouse.c.s

.PHONY : Libraries/usr/ginput_lld_mouse.s

# target to generate assembly for a file
Libraries/usr/ginput_lld_mouse.c.s:
	$(MAKE) -f CMakeFiles/usrlib.dir/build.make CMakeFiles/usrlib.dir/Libraries/usr/ginput_lld_mouse.c.s
.PHONY : Libraries/usr/ginput_lld_mouse.c.s

Libraries/usr/port.o: Libraries/usr/port.c.o

.PHONY : Libraries/usr/port.o

# target to build an object file
Libraries/usr/port.c.o:
	$(MAKE) -f CMakeFiles/usrlib.dir/build.make CMakeFiles/usrlib.dir/Libraries/usr/port.c.o
.PHONY : Libraries/usr/port.c.o

Libraries/usr/port.i: Libraries/usr/port.c.i

.PHONY : Libraries/usr/port.i

# target to preprocess a source file
Libraries/usr/port.c.i:
	$(MAKE) -f CMakeFiles/usrlib.dir/build.make CMakeFiles/usrlib.dir/Libraries/usr/port.c.i
.PHONY : Libraries/usr/port.c.i

Libraries/usr/port.s: Libraries/usr/port.c.s

.PHONY : Libraries/usr/port.s

# target to generate assembly for a file
Libraries/usr/port.c.s:
	$(MAKE) -f CMakeFiles/usrlib.dir/build.make CMakeFiles/usrlib.dir/Libraries/usr/port.c.s
.PHONY : Libraries/usr/port.c.s

Libraries/usr/startup_stm32f429_439xx.o: Libraries/usr/startup_stm32f429_439xx.S.o

.PHONY : Libraries/usr/startup_stm32f429_439xx.o

# target to build an object file
Libraries/usr/startup_stm32f429_439xx.S.o:
	$(MAKE) -f CMakeFiles/usrlib.dir/build.make CMakeFiles/usrlib.dir/Libraries/usr/startup_stm32f429_439xx.S.o
.PHONY : Libraries/usr/startup_stm32f429_439xx.S.o

Libraries/usr/system_stm32f4xx.o: Libraries/usr/system_stm32f4xx.c.o

.PHONY : Libraries/usr/system_stm32f4xx.o

# target to build an object file
Libraries/usr/system_stm32f4xx.c.o:
	$(MAKE) -f CMakeFiles/usrlib.dir/build.make CMakeFiles/usrlib.dir/Libraries/usr/system_stm32f4xx.c.o
.PHONY : Libraries/usr/system_stm32f4xx.c.o

Libraries/usr/system_stm32f4xx.i: Libraries/usr/system_stm32f4xx.c.i

.PHONY : Libraries/usr/system_stm32f4xx.i

# target to preprocess a source file
Libraries/usr/system_stm32f4xx.c.i:
	$(MAKE) -f CMakeFiles/usrlib.dir/build.make CMakeFiles/usrlib.dir/Libraries/usr/system_stm32f4xx.c.i
.PHONY : Libraries/usr/system_stm32f4xx.c.i

Libraries/usr/system_stm32f4xx.s: Libraries/usr/system_stm32f4xx.c.s

.PHONY : Libraries/usr/system_stm32f4xx.s

# target to generate assembly for a file
Libraries/usr/system_stm32f4xx.c.s:
	$(MAKE) -f CMakeFiles/usrlib.dir/build.make CMakeFiles/usrlib.dir/Libraries/usr/system_stm32f4xx.c.s
.PHONY : Libraries/usr/system_stm32f4xx.c.s

Libraries/usr/timertest.o: Libraries/usr/timertest.c.o

.PHONY : Libraries/usr/timertest.o

# target to build an object file
Libraries/usr/timertest.c.o:
	$(MAKE) -f CMakeFiles/usrlib.dir/build.make CMakeFiles/usrlib.dir/Libraries/usr/timertest.c.o
.PHONY : Libraries/usr/timertest.c.o

Libraries/usr/timertest.i: Libraries/usr/timertest.c.i

.PHONY : Libraries/usr/timertest.i

# target to preprocess a source file
Libraries/usr/timertest.c.i:
	$(MAKE) -f CMakeFiles/usrlib.dir/build.make CMakeFiles/usrlib.dir/Libraries/usr/timertest.c.i
.PHONY : Libraries/usr/timertest.c.i

Libraries/usr/timertest.s: Libraries/usr/timertest.c.s

.PHONY : Libraries/usr/timertest.s

# target to generate assembly for a file
Libraries/usr/timertest.c.s:
	$(MAKE) -f CMakeFiles/usrlib.dir/build.make CMakeFiles/usrlib.dir/Libraries/usr/timertest.c.s
.PHONY : Libraries/usr/timertest.c.s

code/Demo.o: code/Demo.c.o

.PHONY : code/Demo.o

# target to build an object file
code/Demo.c.o:
	$(MAKE) -f CMakeFiles/usrlib.dir/build.make CMakeFiles/usrlib.dir/code/Demo.c.o
.PHONY : code/Demo.c.o

code/Demo.i: code/Demo.c.i

.PHONY : code/Demo.i

# target to preprocess a source file
code/Demo.c.i:
	$(MAKE) -f CMakeFiles/usrlib.dir/build.make CMakeFiles/usrlib.dir/code/Demo.c.i
.PHONY : code/Demo.c.i

code/Demo.s: code/Demo.c.s

.PHONY : code/Demo.s

# target to generate assembly for a file
code/Demo.c.s:
	$(MAKE) -f CMakeFiles/usrlib.dir/build.make CMakeFiles/usrlib.dir/code/Demo.c.s
.PHONY : code/Demo.c.s

code/buttonDebounce.o: code/buttonDebounce.c.o

.PHONY : code/buttonDebounce.o

# target to build an object file
code/buttonDebounce.c.o:
	$(MAKE) -f CMakeFiles/usrlib.dir/build.make CMakeFiles/usrlib.dir/code/buttonDebounce.c.o
.PHONY : code/buttonDebounce.c.o

code/buttonDebounce.i: code/buttonDebounce.c.i

.PHONY : code/buttonDebounce.i

# target to preprocess a source file
code/buttonDebounce.c.i:
	$(MAKE) -f CMakeFiles/usrlib.dir/build.make CMakeFiles/usrlib.dir/code/buttonDebounce.c.i
.PHONY : code/buttonDebounce.c.i

code/buttonDebounce.s: code/buttonDebounce.c.s

.PHONY : code/buttonDebounce.s

# target to generate assembly for a file
code/buttonDebounce.c.s:
	$(MAKE) -f CMakeFiles/usrlib.dir/build.make CMakeFiles/usrlib.dir/code/buttonDebounce.c.s
.PHONY : code/buttonDebounce.c.s

code/buttons.o: code/buttons.c.o

.PHONY : code/buttons.o

# target to build an object file
code/buttons.c.o:
	$(MAKE) -f CMakeFiles/usrlib.dir/build.make CMakeFiles/usrlib.dir/code/buttons.c.o
.PHONY : code/buttons.c.o

code/buttons.i: code/buttons.c.i

.PHONY : code/buttons.i

# target to preprocess a source file
code/buttons.c.i:
	$(MAKE) -f CMakeFiles/usrlib.dir/build.make CMakeFiles/usrlib.dir/code/buttons.c.i
.PHONY : code/buttons.c.i

code/buttons.s: code/buttons.c.s

.PHONY : code/buttons.s

# target to generate assembly for a file
code/buttons.c.s:
	$(MAKE) -f CMakeFiles/usrlib.dir/build.make CMakeFiles/usrlib.dir/code/buttons.c.s
.PHONY : code/buttons.c.s

code/exercise3TaskCode.o: code/exercise3TaskCode.c.o

.PHONY : code/exercise3TaskCode.o

# target to build an object file
code/exercise3TaskCode.c.o:
	$(MAKE) -f CMakeFiles/usrlib.dir/build.make CMakeFiles/usrlib.dir/code/exercise3TaskCode.c.o
.PHONY : code/exercise3TaskCode.c.o

code/exercise3TaskCode.i: code/exercise3TaskCode.c.i

.PHONY : code/exercise3TaskCode.i

# target to preprocess a source file
code/exercise3TaskCode.c.i:
	$(MAKE) -f CMakeFiles/usrlib.dir/build.make CMakeFiles/usrlib.dir/code/exercise3TaskCode.c.i
.PHONY : code/exercise3TaskCode.c.i

code/exercise3TaskCode.s: code/exercise3TaskCode.c.s

.PHONY : code/exercise3TaskCode.s

# target to generate assembly for a file
code/exercise3TaskCode.c.s:
	$(MAKE) -f CMakeFiles/usrlib.dir/build.make CMakeFiles/usrlib.dir/code/exercise3TaskCode.c.s
.PHONY : code/exercise3TaskCode.c.s

code/exercise4.o: code/exercise4.c.o

.PHONY : code/exercise4.o

# target to build an object file
code/exercise4.c.o:
	$(MAKE) -f CMakeFiles/usrlib.dir/build.make CMakeFiles/usrlib.dir/code/exercise4.c.o
.PHONY : code/exercise4.c.o

code/exercise4.i: code/exercise4.c.i

.PHONY : code/exercise4.i

# target to preprocess a source file
code/exercise4.c.i:
	$(MAKE) -f CMakeFiles/usrlib.dir/build.make CMakeFiles/usrlib.dir/code/exercise4.c.i
.PHONY : code/exercise4.c.i

code/exercise4.s: code/exercise4.c.s

.PHONY : code/exercise4.s

# target to generate assembly for a file
code/exercise4.c.s:
	$(MAKE) -f CMakeFiles/usrlib.dir/build.make CMakeFiles/usrlib.dir/code/exercise4.c.s
.PHONY : code/exercise4.c.s

code/staticFunctions.o: code/staticFunctions.c.o

.PHONY : code/staticFunctions.o

# target to build an object file
code/staticFunctions.c.o:
	$(MAKE) -f CMakeFiles/usrlib.dir/build.make CMakeFiles/usrlib.dir/code/staticFunctions.c.o
.PHONY : code/staticFunctions.c.o

code/staticFunctions.i: code/staticFunctions.c.i

.PHONY : code/staticFunctions.i

# target to preprocess a source file
code/staticFunctions.c.i:
	$(MAKE) -f CMakeFiles/usrlib.dir/build.make CMakeFiles/usrlib.dir/code/staticFunctions.c.i
.PHONY : code/staticFunctions.c.i

code/staticFunctions.s: code/staticFunctions.c.s

.PHONY : code/staticFunctions.s

# target to generate assembly for a file
code/staticFunctions.c.s:
	$(MAKE) -f CMakeFiles/usrlib.dir/build.make CMakeFiles/usrlib.dir/code/staticFunctions.c.s
.PHONY : code/staticFunctions.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... flash"
	@echo "... ugfxlib"
	@echo "... usrlib"
	@echo "... Demo.bin"
	@echo "... stmutilitieslib"
	@echo "... rtoslib"
	@echo "... Demo.elf"
	@echo "... stmperipheralslib"
	@echo "... Libraries/FreeRTOS/FreeRTOS/Demo/Common/Minimal/flash.o"
	@echo "... Libraries/FreeRTOS/FreeRTOS/Demo/Common/Minimal/flash.i"
	@echo "... Libraries/FreeRTOS/FreeRTOS/Demo/Common/Minimal/flash.s"
	@echo "... Libraries/FreeRTOS/FreeRTOS/Source/list.o"
	@echo "... Libraries/FreeRTOS/FreeRTOS/Source/list.i"
	@echo "... Libraries/FreeRTOS/FreeRTOS/Source/list.s"
	@echo "... Libraries/FreeRTOS/FreeRTOS/Source/portable/MemMang/heap_1.o"
	@echo "... Libraries/FreeRTOS/FreeRTOS/Source/portable/MemMang/heap_1.i"
	@echo "... Libraries/FreeRTOS/FreeRTOS/Source/portable/MemMang/heap_1.s"
	@echo "... Libraries/FreeRTOS/FreeRTOS/Source/queue.o"
	@echo "... Libraries/FreeRTOS/FreeRTOS/Source/queue.i"
	@echo "... Libraries/FreeRTOS/FreeRTOS/Source/queue.s"
	@echo "... Libraries/FreeRTOS/FreeRTOS/Source/tasks.o"
	@echo "... Libraries/FreeRTOS/FreeRTOS/Source/tasks.i"
	@echo "... Libraries/FreeRTOS/FreeRTOS/Source/tasks.s"
	@echo "... Libraries/FreeRTOS/FreeRTOS/Source/timers.o"
	@echo "... Libraries/FreeRTOS/FreeRTOS/Source/timers.i"
	@echo "... Libraries/FreeRTOS/FreeRTOS/Source/timers.s"
	@echo "... Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/misc.o"
	@echo "... Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/misc.i"
	@echo "... Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/misc.s"
	@echo "... Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_adc.o"
	@echo "... Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_adc.i"
	@echo "... Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_adc.s"
	@echo "... Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dma.o"
	@echo "... Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dma.i"
	@echo "... Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dma.s"
	@echo "... Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dma2d.o"
	@echo "... Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dma2d.i"
	@echo "... Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dma2d.s"
	@echo "... Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_exti.o"
	@echo "... Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_exti.i"
	@echo "... Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_exti.s"
	@echo "... Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_fmc.o"
	@echo "... Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_fmc.i"
	@echo "... Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_fmc.s"
	@echo "... Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_gpio.o"
	@echo "... Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_gpio.i"
	@echo "... Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_gpio.s"
	@echo "... Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_i2c.o"
	@echo "... Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_i2c.i"
	@echo "... Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_i2c.s"
	@echo "... Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_ltdc.o"
	@echo "... Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_ltdc.i"
	@echo "... Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_ltdc.s"
	@echo "... Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rcc.o"
	@echo "... Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rcc.i"
	@echo "... Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rcc.s"
	@echo "... Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_spi.o"
	@echo "... Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_spi.i"
	@echo "... Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_spi.s"
	@echo "... Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_syscfg.o"
	@echo "... Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_syscfg.i"
	@echo "... Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_syscfg.s"
	@echo "... Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_tim.o"
	@echo "... Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_tim.i"
	@echo "... Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_tim.s"
	@echo "... Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_usart.o"
	@echo "... Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_usart.i"
	@echo "... Libraries/STM32F4/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_usart.s"
	@echo "... Libraries/STM32F4/Utilities/STM32_EVAL/STM32F429I-Discovery/stm32f429i_discovery_ioe.o"
	@echo "... Libraries/STM32F4/Utilities/STM32_EVAL/STM32F429I-Discovery/stm32f429i_discovery_ioe.i"
	@echo "... Libraries/STM32F4/Utilities/STM32_EVAL/STM32F429I-Discovery/stm32f429i_discovery_ioe.s"
	@echo "... Libraries/STM32F4/Utilities/STM32_EVAL/STM32F429I-Discovery/stm32f429i_discovery_lcd.o"
	@echo "... Libraries/STM32F4/Utilities/STM32_EVAL/STM32F429I-Discovery/stm32f429i_discovery_lcd.i"
	@echo "... Libraries/STM32F4/Utilities/STM32_EVAL/STM32F429I-Discovery/stm32f429i_discovery_lcd.s"
	@echo "... Libraries/STM32F4/Utilities/STM32_EVAL/STM32F429I-Discovery/stm32f429i_discovery_sdram.o"
	@echo "... Libraries/STM32F4/Utilities/STM32_EVAL/STM32F429I-Discovery/stm32f429i_discovery_sdram.i"
	@echo "... Libraries/STM32F4/Utilities/STM32_EVAL/STM32F429I-Discovery/stm32f429i_discovery_sdram.s"
	@echo "... Libraries/ugfx/src/gdisp/gdisp.o"
	@echo "... Libraries/ugfx/src/gdisp/gdisp.i"
	@echo "... Libraries/ugfx/src/gdisp/gdisp.s"
	@echo "... Libraries/ugfx/src/gdisp/gdisp_fonts.o"
	@echo "... Libraries/ugfx/src/gdisp/gdisp_fonts.i"
	@echo "... Libraries/ugfx/src/gdisp/gdisp_fonts.s"
	@echo "... Libraries/ugfx/src/gdisp/mcufont/mf_encoding.o"
	@echo "... Libraries/ugfx/src/gdisp/mcufont/mf_encoding.i"
	@echo "... Libraries/ugfx/src/gdisp/mcufont/mf_encoding.s"
	@echo "... Libraries/ugfx/src/gdisp/mcufont/mf_font.o"
	@echo "... Libraries/ugfx/src/gdisp/mcufont/mf_font.i"
	@echo "... Libraries/ugfx/src/gdisp/mcufont/mf_font.s"
	@echo "... Libraries/ugfx/src/gdisp/mcufont/mf_justify.o"
	@echo "... Libraries/ugfx/src/gdisp/mcufont/mf_justify.i"
	@echo "... Libraries/ugfx/src/gdisp/mcufont/mf_justify.s"
	@echo "... Libraries/ugfx/src/gdisp/mcufont/mf_rlefont.o"
	@echo "... Libraries/ugfx/src/gdisp/mcufont/mf_rlefont.i"
	@echo "... Libraries/ugfx/src/gdisp/mcufont/mf_rlefont.s"
	@echo "... Libraries/ugfx/src/gdisp/mcufont/mf_scaledfont.o"
	@echo "... Libraries/ugfx/src/gdisp/mcufont/mf_scaledfont.i"
	@echo "... Libraries/ugfx/src/gdisp/mcufont/mf_scaledfont.s"
	@echo "... Libraries/ugfx/src/gdriver/gdriver.o"
	@echo "... Libraries/ugfx/src/gdriver/gdriver.i"
	@echo "... Libraries/ugfx/src/gdriver/gdriver.s"
	@echo "... Libraries/ugfx/src/gevent/gevent.o"
	@echo "... Libraries/ugfx/src/gevent/gevent.i"
	@echo "... Libraries/ugfx/src/gevent/gevent.s"
	@echo "... Libraries/ugfx/src/gfx.o"
	@echo "... Libraries/ugfx/src/gfx.i"
	@echo "... Libraries/ugfx/src/gfx.s"
	@echo "... Libraries/ugfx/src/ginput/ginput.o"
	@echo "... Libraries/ugfx/src/ginput/ginput.i"
	@echo "... Libraries/ugfx/src/ginput/ginput.s"
	@echo "... Libraries/ugfx/src/ginput/ginput_mouse.o"
	@echo "... Libraries/ugfx/src/ginput/ginput_mouse.i"
	@echo "... Libraries/ugfx/src/ginput/ginput_mouse.s"
	@echo "... Libraries/ugfx/src/gos/gos_freertos.o"
	@echo "... Libraries/ugfx/src/gos/gos_freertos.i"
	@echo "... Libraries/ugfx/src/gos/gos_freertos.s"
	@echo "... Libraries/ugfx/src/gtimer/gtimer.o"
	@echo "... Libraries/ugfx/src/gtimer/gtimer.i"
	@echo "... Libraries/ugfx/src/gtimer/gtimer.s"
	@echo "... Libraries/ugfx/src/gwin/gwin.o"
	@echo "... Libraries/ugfx/src/gwin/gwin.i"
	@echo "... Libraries/ugfx/src/gwin/gwin.s"
	@echo "... Libraries/ugfx/src/gwin/gwin_console.o"
	@echo "... Libraries/ugfx/src/gwin/gwin_console.i"
	@echo "... Libraries/ugfx/src/gwin/gwin_console.s"
	@echo "... Libraries/ugfx/src/gwin/gwin_wm.o"
	@echo "... Libraries/ugfx/src/gwin/gwin_wm.i"
	@echo "... Libraries/ugfx/src/gwin/gwin_wm.s"
	@echo "... Libraries/usr/ESPL_functions.o"
	@echo "... Libraries/usr/ESPL_functions.i"
	@echo "... Libraries/usr/ESPL_functions.s"
	@echo "... Libraries/usr/ParTest.o"
	@echo "... Libraries/usr/ParTest.i"
	@echo "... Libraries/usr/ParTest.s"
	@echo "... Libraries/usr/gdisp_lld_ILI9341.o"
	@echo "... Libraries/usr/gdisp_lld_ILI9341.i"
	@echo "... Libraries/usr/gdisp_lld_ILI9341.s"
	@echo "... Libraries/usr/ginput_lld_mouse.o"
	@echo "... Libraries/usr/ginput_lld_mouse.i"
	@echo "... Libraries/usr/ginput_lld_mouse.s"
	@echo "... Libraries/usr/port.o"
	@echo "... Libraries/usr/port.i"
	@echo "... Libraries/usr/port.s"
	@echo "... Libraries/usr/startup_stm32f429_439xx.o"
	@echo "... Libraries/usr/system_stm32f4xx.o"
	@echo "... Libraries/usr/system_stm32f4xx.i"
	@echo "... Libraries/usr/system_stm32f4xx.s"
	@echo "... Libraries/usr/timertest.o"
	@echo "... Libraries/usr/timertest.i"
	@echo "... Libraries/usr/timertest.s"
	@echo "... code/Demo.o"
	@echo "... code/Demo.i"
	@echo "... code/Demo.s"
	@echo "... code/buttonDebounce.o"
	@echo "... code/buttonDebounce.i"
	@echo "... code/buttonDebounce.s"
	@echo "... code/buttons.o"
	@echo "... code/buttons.i"
	@echo "... code/buttons.s"
	@echo "... code/exercise3TaskCode.o"
	@echo "... code/exercise3TaskCode.i"
	@echo "... code/exercise3TaskCode.s"
	@echo "... code/exercise4.o"
	@echo "... code/exercise4.i"
	@echo "... code/exercise4.s"
	@echo "... code/staticFunctions.o"
	@echo "... code/staticFunctions.i"
	@echo "... code/staticFunctions.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

